app = "ReMind"

[build]
  builtin = "python"  # Let Fly use the Python buildpack

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[experimental]
  cmd = ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
